name: CI Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Install dependencies
        run: |
          cd backend
          go mod tidy

      - name: Run tests (placeholder)
        run: |
          echo "No tests available yet."

      - name: Build the project
        run: |
          go build -o moneywise
