name: CI Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.5"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          cd backend
          go mod tidy

      # Step 4: Run tests (if you have any)
      - name: Run tests (placeholder)
        run: |
          cd backend
          echo "No tests available yet."

      # Step 5: Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t javy1999/moneywise-auth:latest -f backend/docker/auth/Dockerfile .

      # Step 6: Log in to Docker Hub (or your private registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Push Docker image to Docker Hub (or your registry)
      - name: Push Docker image
        run: |
          docker push javy1999/moneywise-auth:latest

      - name: Build the project
        run: |
          cd backend/cmd/auth
          go build
