name: Deploy to Kubernetes

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Kubernetes CLI (kubectl)
      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v3

      # Step 3: Set up Minikube (for local Kubernetes cluster)
      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo mv minikube-linux-amd64 /usr/local/bin/minikube
          sudo chmod +x /usr/local/bin/minikube
          minikube start --driver=docker

      # Step 4: Set up Docker Buildx (for Docker support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Pull the Docker image from Docker Hub
      - name: Pull Docker image
        run: |
          docker pull javy1999/moneywise-auth:latest

      # Step 7: Set up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v2

      # Step 8: Configure kubectl to use Minikube's Kubernetes context
      - name: Set up kubectl to use Minikube
        run: |
          kubectl config use-context minikube

      # Step 9: Deploy using Helm
      - name: Deploy using Helm
        run: |
          helm upgrade --install auth-release .backend/helm/auth --namespace javy --set image.repository=javy1999/moneywise-auth,image.tag=latest

      # Step 10: Expose the service (if needed)
      - name: Expose the service (Optional for Minikube)
        run: |
          minikube service auth-service --url --namespace javy
